[project]
name = "deepchronos"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "deepproblog>=2.0.6",
    "pandas>=2.3.3",
    "scikit-learn>=1.7.2",
]
